version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.10

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.10
    steps:
      - checkout
      - run:
          command: |
            apk add bash
            name='<h1>takuya</h1>'
            if [[ $name =~ takuya ]] ;
            then
            echo ${BASH_REMATCH[@]}
            fi          
        
workflows:
  shellcheck:
    jobs:
      - shellcheck/check
      - build
